#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it’s executed on
ip -o -4 addr show \
  | grep -E 'scope (global|host)' \
  | awk '$3=="inet"{print $4}' \
  | cut -d/ -f1
